// Package apigateway provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package apigateway

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyScopes = "apiKey.Scopes"
)

// Defines values for ThingType.
const (
	Any  ThingType = "any"
	None ThingType = "none"
	Some ThingType = "some"
)

// CreateThingRequest defines model for CreateThingRequest.
type CreateThingRequest struct {
	Name   string    `json:"name"`
	Rank   int64     `json:"rank"`
	Rating *float32  `json:"rating,omitempty"`
	Score  *float64  `json:"score,omitempty"`
	Type   ThingType `json:"type"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ListThingsResponse defines model for ListThingsResponse.
type ListThingsResponse struct {
	Things []ThingResponse `json:"things"`
	Total  int             `json:"total"`
}

// ThingResponse defines model for ThingResponse.
type ThingResponse struct {
	Created time.Time          `json:"created"`
	Name    string             `json:"name"`
	Rank    int64              `json:"rank"`
	Rating  float32            `json:"rating"`
	Score   float64            `json:"score"`
	Type    ThingType          `json:"type"`
	Uuid    openapi_types.UUID `json:"uuid"`
}

// ThingType defines model for ThingType.
type ThingType string

// UpdateThingRequest defines model for UpdateThingRequest.
type UpdateThingRequest struct {
	Score float64 `json:"score"`
}

// DefaultError defines model for DefaultError.
type DefaultError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListThingsParams defines parameters for ListThings.
type ListThingsParams struct {
	// Page Page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Keyword Filter things by keyword
	Keyword *string `form:"keyword,omitempty" json:"keyword,omitempty"`
}

// CreateThingJSONRequestBody defines body for CreateThing for application/json ContentType.
type CreateThingJSONRequestBody = CreateThingRequest

// UpdateThingJSONRequestBody defines body for UpdateThing for application/json ContentType.
type UpdateThingJSONRequestBody = UpdateThingRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /things)
	ListThings(c *gin.Context, params ListThingsParams)

	// (POST /things)
	CreateThing(c *gin.Context)

	// (DELETE /things/{uuid})
	DeleteThing(c *gin.Context, uuid openapi_types.UUID)

	// (GET /things/{uuid})
	GetThing(c *gin.Context, uuid openapi_types.UUID)

	// (PUT /things/{uuid})
	UpdateThing(c *gin.Context, uuid openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListThings operation middleware
func (siw *ServerInterfaceWrapper) ListThings(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListThingsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "keyword" -------------

	err = runtime.BindQueryParameter("form", true, false, "keyword", c.Request.URL.Query(), &params.Keyword)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter keyword: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListThings(c, params)
}

// CreateThing operation middleware
func (siw *ServerInterfaceWrapper) CreateThing(c *gin.Context) {

	c.Set(ApiKeyScopes, []string{"thing.create"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateThing(c)
}

// DeleteThing operation middleware
func (siw *ServerInterfaceWrapper) DeleteThing(c *gin.Context) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "uuid", c.Param("uuid"), &uuid)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uuid: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyScopes, []string{"thing.delete"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteThing(c, uuid)
}

// GetThing operation middleware
func (siw *ServerInterfaceWrapper) GetThing(c *gin.Context) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "uuid", c.Param("uuid"), &uuid)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uuid: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetThing(c, uuid)
}

// UpdateThing operation middleware
func (siw *ServerInterfaceWrapper) UpdateThing(c *gin.Context) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "uuid", c.Param("uuid"), &uuid)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uuid: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyScopes, []string{"thing.update"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateThing(c, uuid)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/things", wrapper.ListThings)
	router.POST(options.BaseURL+"/things", wrapper.CreateThing)
	router.DELETE(options.BaseURL+"/things/:uuid", wrapper.DeleteThing)
	router.GET(options.BaseURL+"/things/:uuid", wrapper.GetThing)
	router.PUT(options.BaseURL+"/things/:uuid", wrapper.UpdateThing)
}

type DefaultErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListThingsRequestObject struct {
	Params ListThingsParams
}

type ListThingsResponseObject interface {
	VisitListThingsResponse(w http.ResponseWriter) error
}

type ListThings200JSONResponse ListThingsResponse

func (response ListThings200JSONResponse) VisitListThingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListThings401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListThings401JSONResponse) VisitListThingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListThingsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListThingsdefaultJSONResponse) VisitListThingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateThingRequestObject struct {
	Body *CreateThingJSONRequestBody
}

type CreateThingResponseObject interface {
	VisitCreateThingResponse(w http.ResponseWriter) error
}

type CreateThing200JSONResponse ThingResponse

func (response CreateThing200JSONResponse) VisitCreateThingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateThingdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateThingdefaultJSONResponse) VisitCreateThingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteThingRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
}

type DeleteThingResponseObject interface {
	VisitDeleteThingResponse(w http.ResponseWriter) error
}

type DeleteThing204Response struct {
}

func (response DeleteThing204Response) VisitDeleteThingResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteThing401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteThing401JSONResponse) VisitDeleteThingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteThing404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteThing404JSONResponse) VisitDeleteThingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteThingdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteThingdefaultJSONResponse) VisitDeleteThingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetThingRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
}

type GetThingResponseObject interface {
	VisitGetThingResponse(w http.ResponseWriter) error
}

type GetThing200JSONResponse ThingResponse

func (response GetThing200JSONResponse) VisitGetThingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetThing401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetThing401JSONResponse) VisitGetThingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetThing404JSONResponse struct{ NotFoundJSONResponse }

func (response GetThing404JSONResponse) VisitGetThingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetThingdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetThingdefaultJSONResponse) VisitGetThingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateThingRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *UpdateThingJSONRequestBody
}

type UpdateThingResponseObject interface {
	VisitUpdateThingResponse(w http.ResponseWriter) error
}

type UpdateThing204Response struct {
}

func (response UpdateThing204Response) VisitUpdateThingResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateThing401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateThing401JSONResponse) VisitUpdateThingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateThing404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateThing404JSONResponse) VisitUpdateThingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateThingdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpdateThingdefaultJSONResponse) VisitUpdateThingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /things)
	ListThings(ctx context.Context, request ListThingsRequestObject) (ListThingsResponseObject, error)

	// (POST /things)
	CreateThing(ctx context.Context, request CreateThingRequestObject) (CreateThingResponseObject, error)

	// (DELETE /things/{uuid})
	DeleteThing(ctx context.Context, request DeleteThingRequestObject) (DeleteThingResponseObject, error)

	// (GET /things/{uuid})
	GetThing(ctx context.Context, request GetThingRequestObject) (GetThingResponseObject, error)

	// (PUT /things/{uuid})
	UpdateThing(ctx context.Context, request UpdateThingRequestObject) (UpdateThingResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListThings operation middleware
func (sh *strictHandler) ListThings(ctx *gin.Context, params ListThingsParams) {
	var request ListThingsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListThings(ctx, request.(ListThingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListThings")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListThingsResponseObject); ok {
		if err := validResponse.VisitListThingsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateThing operation middleware
func (sh *strictHandler) CreateThing(ctx *gin.Context) {
	var request CreateThingRequestObject

	var body CreateThingJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateThing(ctx, request.(CreateThingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateThing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateThingResponseObject); ok {
		if err := validResponse.VisitCreateThingResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteThing operation middleware
func (sh *strictHandler) DeleteThing(ctx *gin.Context, uuid openapi_types.UUID) {
	var request DeleteThingRequestObject

	request.Uuid = uuid

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteThing(ctx, request.(DeleteThingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteThing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteThingResponseObject); ok {
		if err := validResponse.VisitDeleteThingResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetThing operation middleware
func (sh *strictHandler) GetThing(ctx *gin.Context, uuid openapi_types.UUID) {
	var request GetThingRequestObject

	request.Uuid = uuid

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetThing(ctx, request.(GetThingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetThing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetThingResponseObject); ok {
		if err := validResponse.VisitGetThingResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateThing operation middleware
func (sh *strictHandler) UpdateThing(ctx *gin.Context, uuid openapi_types.UUID) {
	var request UpdateThingRequestObject

	request.Uuid = uuid

	var body UpdateThingJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateThing(ctx, request.(UpdateThingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateThing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateThingResponseObject); ok {
		if err := validResponse.VisitUpdateThingResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xX32/bNhD+Vzhuj4zlZNke9LSsTYusQVa0KTAgyAMjnS2mEsmQp3he4P99OFI/bEuO",
	"uyIJuj5ZEsm7433ffXd+4JmprNGg0fP0gTvw1mgP4eU1zGRd4qlzxtF7ZjSCRnqU1pYqk6iMTm690fTN",
	"ZwVUkp5+cjDjKf8x6Y0ncdUn0dpqtRI8B585ZckIT3mzIPiFwTem1vnzu7wsgHkLmZopyJkDb2qXAVtI",
	"z7RBNgtRrAT/pGWNhXHqH3iBqDa80XJzggy+ciARLgul5x/grgYfgrDOWHCoImxaVkC/lfz7HPQcC54e",
	"TgXHpQWeco9O6Tndykn9mfbNjKsk8pQrjb8e826n0ghzcHEr0qH1zbPSSOSCvKiqrnj6i+CV0vG5d6fr",
	"6iba8JlxsGEiN/VNCXxkb/zweP5CEi5pI+XIwV2tHMFzFRPQGGmued05MTe3kCE56Xi9mb7M5MH3IF8V",
	"eC/nY2tb/oOFfv+Y73PlMVzAf2gqbhgIhnV6UgiV/6J8dNa6JHLpnFyGd4OyXIu+w3cr/MZve2As/E1f",
	"wxQGluabYEuEA1TVGt59alvKPhNHX5KLgte12rx6+CD2kGZ9k2gpHK7fhttdUXQJ3onNZRM0aCrHK+5N",
	"sCf1kowbvc7KPtufbL5XXb48dVsXjAeHERMckNVO4fIjpTO6kVa9g2UgP2liATIH1yYm5X8dnFh1QDt6",
	"nscTQVCVnplWqGUWbgGVVGVgzMz8VuZwO9Flb+9c1g50BiwH9ocJOa4dbS8QrU+TpDmR8NEmEkuZnbw/",
	"YxEaL5gDmXvB6pBTL1ipPHomdc5yKAHBs1hoP3DBS5VBU0lNQCdWZgWwo8l0EMpisZjIsDwxbp40Z31y",
	"fvbq9OLj6QGdId4qLCHE18bGBb8H52PYh3GXsaClVTzlP0+mkyMuuJVYBAiSXoDmEHK4eXHSMNaJBXEk",
	"tMGzvFm7bJesdLICBOd5erVt5b2cA2soIyLYdzW4ZY+NJREVa111qF/bRt+oEsE1wbGbJfsMy4Vx+Q4P",
	"/erASVet12JzODqaTp9sFBjpBiNzwZ/vCLDj6eEuc118yeYIQYbCJLf/4MbIRyGgJAY0TYFfrwS3xo+Q",
	"IQ4mTMacD/iwNrfwKAvg8XeTL58shyOT0VgOg+iwoAtKKz2P8caqVUaznquT0FSeC/Ktbr0L7a8HrtXU",
	"UHKtmjY4TqJI8Wti9TbCK9FWfvJATWkVwSbJGsL+OnzfCXtcbmF/VAdIRskdMzOGBTS4oGGkPU3ZkjT1",
	"Vdt0zL7HoKthvYT3NeBhSR8Pb3hhWAv411bfcbT7+KHuX8/zod6AOIq6GNf4t4BMMq/0vIQdGL8F/P8A",
	"/OIF/K0TZkTf6xEexMlwZ52vDY7fKg2evuOMTMv/oePEuXBPv/m+9SimYEcXCofdfUuiOAIn0qrk/pCv",
	"ndjOz6nOrVEaPaP50MmM/jKxhcKin1UbYkVfq+vVvwEAAP//0B2dLAYTAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
